<?php

namespace App\Consts;

class RunClubTokyoConstConst
{
    public const GOAL_TIME = [
        1 => '75分以内',
        2 => '75分～90分',
        3 => '90分～1時間',
        4 => '1時間～1時間15分',
        5 => '1時間15分～1時間30分',
        6 => '1時間30分～1時間45分',
        7 => '1時間45分～2時間',
        8 => '2時間～2時間15分',
        9 => '2時間15分～2時間30分',
        10 => '2時間30分～2時間45分',
        11 => '2時間45分～3時間',
        12 => '完走目標',
    ];

    public const SHOES_SIZE = [
        1 => '22.0',
        2 => '22.5',
        3 => '23.0',
        4 => '23.5',
        5 => '24.0',
        6 => '24.5',
        7 => '25.0',
        8 => '25.5',
        9 => '26.0',
        10 => '26.5',
        11 => '27.0',
        12 => '27.5',
        13 => '28.0',
        14 => '28.5',
        15 => '29.0',
    ];

    public const TARGETS = [
        'gohan.oomori38@gmail.com',
        'pite-3078@i.softbank.jp',
        'mimimi.kitazon.39@docomo.ne.jp',
        'vnkanone@yahoo.co.jp',
        'sh1.ota@kki.biglobe.ne.jp',
        't.kat1012@gmail.com',
        'syun_mama.kurumi0@docomo.ne.jp',
        'yoshki04@gmail.com',
        'scratch7red@gmail.com',
        'bokenaizo_0626@icloud.com',
        'akiko2525-333@i.softbank.jp',
        'ichirossi8@gmail.com',
        'pleasant.703.endo@gmail.com',
        'takako@fuji.email.ne.jp',
        'o_chan304@yahoo.co.jp',
        'flower.mu25@gmail.com',
        'aigi1972@yahoo.co.jp',
        'takuya.shiga@zensho.com',
        'tsukudakaori@hotmail.com',
        'takashiiwai0315@gmail.com',
        'leia_organa_solo@hotmail.com',
        'RXV12074@nifty.com',
        'golgo824@ezweb.ne.jp',
        'harry2u@mac.com',
        'skinow98@hotmail.com',
        'k-attacker@helen.ocn.ne.jp',
        'eb26airin@yahoo.co.jp',
        'naohiro.terakawa@gmail.com',
        'h.yamaoka7788@gmail.com',
        'so_taboo_two2two@yahoo.co.jp',
        'clubyamaha.xjr@gmail.com',
        'xmarverick@gmail.com',
        'kai_makiko@yahoo.co.jp',
        'kenji85980484@docomo.ne.jp',
        'maho928sasai@docomo.ne.jp',
        'nananoka7@yahoo.co.jp',
        'zx25120@yahoo.co.jp',
        'etsujiro4311@icloud.com',
        'm_nao_f20@yahoo.co.jp',
        'knj117s@yahoo.co.jp',
        'sshaukkiae@gmail.com',
        'saika_n_7102@yahoo.co.jp',
        'saf1_sa07_taku_canada@yahoo.co.jp',
        'nao703-yasumasa@docomo.ne.jp',
        'mk84398yk77sk@gmail.com',
        'forget_me_not0310@yahoo.co.jp',
        'toshiao0712@yahoo.co.jp',
        'u900santa@icloud.com',
        'km_mks21@a.toshima.ne.jp',
        'takawai277@yahoo.co.jp',
    ];

}
